version: '3'

services:
  linux:
    build:
      context: .
      dockerfile: ./docker/ubuntu/Dockerfile
    container_name: "linux"
    environment:
      TZ: Japan
    working_dir: "/root/workspace"
    volumes:
      - ./workspace:/root/workspace
    security_opt:
      - seccomp:unconfined
